---

- name: Include Linux system optimization
  include: system_optimization.yml
  tags: [mongodb]

- include_vars: "{{ansible_distribution}}.yml"

- include: "{{ansible_os_family}}/install.yml"
  tags: [mongodb]

- name: Include configuration.yml
  include: configure.yml
  tags: [mongodb]

- name: Include replication and auth configuration
  include: replication_init_auth.yml
  when: ( mongodb_replication_replset
        and mongodb_replication_replset != ''
        and mongodb_security_authorization == 'enabled'
        and mongodb_master is defined and mongodb_master )
  tags: [mongodb]

- name: Include replication configuration
  include: replication.yml
  when: ( mongodb_replication_replset 
        and mongodb_replication_replset != '' )
  tags: [mongodb]

- name: Include user creation
  include: create_users.yml
  when: mongodb_security_authorization == 'enabled'
  tags: [mongodb]

- name: Install Automation Agent
  include: mms-agent.yml
  when: mongodb_mms_api_key != ""
  tags: [mongodb]

