---

- name: Ensure YUM official mongo repository
  template: src=mongo.repo.j2 dest=/etc/yum.repos.d/mongo.repo

- name: Install MongoDB package
  yum: name={{item}} state=present
  with_items:
    - "{{mongodb_package}}"

- name: Ensure dbpath directory
  file: path={{mongodb_storage_dbpath}} state=directory owner={{ mongodb_user }} recurse=yes

- name: Install PyMongo package
  yum: name=python-pymongo state=latest
  when: not mongodb_pymongo_from_pip

- name: Install PyMongo from PIP
  pip: name=pymongo version="{{ mongodb_pymongo_pip_version }}" state=present
  when: mongodb_pymongo_from_pip
